--Droping Galam Tables
drop table tblForecastTransactions
drop table tblSales
drop table tblUserTypesVsPermissionTypes
drop table tblUsersVsPermissionTypes
drop table tblPermissionTypes
drop table tblUsersVsUserTypes
drop table tblUserTypes
drop table tblUsers
drop table tblShipTos
drop table tblCustomers
drop table tblCountries
drop table tblSaleMenager
drop table tblPeople
drop table tblWeeks
drop table tblPeriods
drop table tblItems
drop table tblFrProductFamilies
drop table tblProductFamilies
drop table tblProductGroups
drop table tblTopGroups